# Introduction

#### PyTorch is an open-source deep learning framework

1. Major components:
  1. Pytorch Tensors
  2. NN Module
  3. Optim Module
  4. Autograd module

2. How do I install PyTorch?
  1. pip3 install torch torchvision
  2. conda install pytorch torchvision -c pytorch


## Contents

1. Pytorch Tensors
  1. Tensor creation
  2. Tensors to Numpy vectors
2. Accessing and modifying data
  1. Tensor indexing
  2. Tensor slicing
3. Pivoting Data
  1. Flatten
  1. Squeeze
  1. Reshape
  1. View
  1. Transpose
  1. Permute
4. Combining tensors
  1. Cat
  2. Stack
  3. Repeat
  4. Repeat Interleave
  5. Padding
5. Mathematical operations
  1. Point-wise/element-wise operations
  1. Redution operations
  1. Comparison operations
  1. Vector/Matrix operations

In [1]:
import torch
torch.manual_seed(0)

## PyTorch Tensor Construction

In [4]:
# Creating tensors without data

t1 = torch.ones(size=(5,3))
t2 = torch.zeros(size=(5,3))
t3 = torch.eye(3)
t4 = torch.rand(size=(3,4))
t5 = torch.arange(7)

print(t1)
print(t2)
print(t3)
print(t4)
print(t5)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320],
        [0.1759, 0.2698, 0.1507, 0.0317]])
tensor([0, 1, 2, 3, 4, 5, 6])


### Creating tensors from existing data

In [8]:
# Creating tensors from existing data ( most comon cases )
import numpy as np

t1 = torch.tensor([1,2,3,4]) # from python list
t2 = torch.tensor(np.array([1,2,3,4])) # from numpy array
t3 = torch.tensor(np.random.randn(3)) # from numpy array
t4 = t3.clone().detach() # from existing torch tensor

print(t1)
print(t2)
print(t3)
print(t4)

tensor([1, 2, 3, 4])
tensor([1, 2, 3, 4])
tensor([ 1.5477, -0.8269,  0.8137], dtype=torch.float64)
tensor([ 1.5477, -0.8269,  0.8137], dtype=torch.float64)


In [9]:
# Convert tensor to numpy array

t1 = torch.tensor([1,2,3,4])
t2 = t1.detach().numpy()

print('Tensor:',t1)
print('Numpy array:',t2)

Tensor: tensor([1, 2, 3, 4])
Numpy array: [1 2 3 4]


## Accessing Tensors
**NOTE:** Tensor values can easily be modified by using the accessing method to select the desired section of the tensor to be modified

In [11]:
# Basic 
t = torch.rand(size=(3,4,5))

print('Original Tensor t:')
print(t)
print('\n')

# Some valid ways of accessing individual elements in the tensor
print('t[0][0][0]\n', t[0][0][0])
print('t[1,2,3]\n', t[1,2,3])
print('t[-1,-1][-1]\n', t[-1,-1][-1])
print('\n')



# Tensor Slicing
print('t[0]\n', t[0])
print('t[:1]\n', t[:1])
print('t[:,1]\n', t[:,1])
print('t[:,:,3]\n', t[:,:,3])
print('t[:,:,-2:]\n', t[:,:,-2:])

Original Tensor t:
tensor([[[0.7497, 0.6047, 0.1100, 0.2121, 0.9704],
         [0.8369, 0.2820, 0.3742, 0.0237, 0.4910],
         [0.1235, 0.1143, 0.4725, 0.5751, 0.2952],
         [0.7967, 0.1957, 0.9537, 0.8426, 0.0784]],

        [[0.3756, 0.5226, 0.5730, 0.6186, 0.6962],
         [0.5300, 0.2560, 0.7366, 0.0204, 0.2036],
         [0.3748, 0.2564, 0.3251, 0.0902, 0.3936],
         [0.6069, 0.1743, 0.4743, 0.8579, 0.4486]],

        [[0.5139, 0.4569, 0.6012, 0.8179, 0.9736],
         [0.8175, 0.9747, 0.4638, 0.0508, 0.2630],
         [0.8405, 0.4968, 0.2515, 0.1168, 0.0321],
         [0.0780, 0.3986, 0.7742, 0.7703, 0.0178]]])


t[0][0][0]
 tensor(0.7497)
t[1,2,3]
 tensor(0.0902)
t[-1,-1][-1]
 tensor(0.0178)


t[0]
 tensor([[0.7497, 0.6047, 0.1100, 0.2121, 0.9704],
        [0.8369, 0.2820, 0.3742, 0.0237, 0.4910],
        [0.1235, 0.1143, 0.4725, 0.5751, 0.2952],
        [0.7967, 0.1957, 0.9537, 0.8426, 0.0784]])
t[:1]
 tensor([[[0.7497, 0.6047, 0.1100, 0.2121, 0.9704],
         [0.8

## Pivoting and Reshaping tensors
In the following section we cover common methods used to pivot and reshape tensors, namely:
1. Flatten
1. Squeeze
1. Reshape
1. View
1. Transpose
1. Permute

In [14]:
# Flatten a tensor

# Flatten the entire tensor. Elements are exhausted in the last dimension first when flattening i.e t[0,0,0] is followed by t[0,0,1] and so on
print(t)
print(t.flatten())

tensor([[[0.7497, 0.6047, 0.1100, 0.2121, 0.9704],
         [0.8369, 0.2820, 0.3742, 0.0237, 0.4910],
         [0.1235, 0.1143, 0.4725, 0.5751, 0.2952],
         [0.7967, 0.1957, 0.9537, 0.8426, 0.0784]],

        [[0.3756, 0.5226, 0.5730, 0.6186, 0.6962],
         [0.5300, 0.2560, 0.7366, 0.0204, 0.2036],
         [0.3748, 0.2564, 0.3251, 0.0902, 0.3936],
         [0.6069, 0.1743, 0.4743, 0.8579, 0.4486]],

        [[0.5139, 0.4569, 0.6012, 0.8179, 0.9736],
         [0.8175, 0.9747, 0.4638, 0.0508, 0.2630],
         [0.8405, 0.4968, 0.2515, 0.1168, 0.0321],
         [0.0780, 0.3986, 0.7742, 0.7703, 0.0178]]])
tensor([0.7497, 0.6047, 0.1100, 0.2121, 0.9704, 0.8369, 0.2820, 0.3742, 0.0237,
        0.4910, 0.1235, 0.1143, 0.4725, 0.5751, 0.2952, 0.7967, 0.1957, 0.9537,
        0.8426, 0.0784, 0.3756, 0.5226, 0.5730, 0.6186, 0.6962, 0.5300, 0.2560,
        0.7366, 0.0204, 0.2036, 0.3748, 0.2564, 0.3251, 0.0902, 0.3936, 0.6069,
        0.1743, 0.4743, 0.8579, 0.4486, 0.5139, 0.4569, 0.6012

In [15]:
# Squeeze and Unsqueeze tensors
# Unsqueeze and squeeze are very handy commands to add and remove a dimension from the tensor.

ts = t.unsqueeze(0)
ts2 = t.unsqueeze(1)

print(ts) # A new dimension is added while all the following dimension are incremented by 1 ( positionally)
print('t.shape:',t.shape)
print('ts.shape:',ts.shape)
print('\n')

print(ts.unsqueeze(0)) # Can apply this operation as many times as required
print('ts.unsqueeze(0).shape:',ts.unsqueeze(0).shape)
print('\n')

print(ts2) # Unsqueeze can also be applied to other intermediate dimensions
print('ts2.shape:',ts2.shape)
print('\n')

print(ts.squeeze(0))
print('ts.squeeze(0).shape:',ts.squeeze(0).shape)
print('\n')

print(ts2.squeeze(1))
print('ts2.squeeze(1).shape:',ts2.squeeze(1).shape)
print('\n')

# print(t.squeeze(0)) squeezing dimensions that have multiple elements have no impacts on the tensor
# print(ts.squeeze(1)) squeezing dimensions that have multiple elements have no impacts on the tensor

tensor([[[[0.7497, 0.6047, 0.1100, 0.2121, 0.9704],
          [0.8369, 0.2820, 0.3742, 0.0237, 0.4910],
          [0.1235, 0.1143, 0.4725, 0.5751, 0.2952],
          [0.7967, 0.1957, 0.9537, 0.8426, 0.0784]],

         [[0.3756, 0.5226, 0.5730, 0.6186, 0.6962],
          [0.5300, 0.2560, 0.7366, 0.0204, 0.2036],
          [0.3748, 0.2564, 0.3251, 0.0902, 0.3936],
          [0.6069, 0.1743, 0.4743, 0.8579, 0.4486]],

         [[0.5139, 0.4569, 0.6012, 0.8179, 0.9736],
          [0.8175, 0.9747, 0.4638, 0.0508, 0.2630],
          [0.8405, 0.4968, 0.2515, 0.1168, 0.0321],
          [0.0780, 0.3986, 0.7742, 0.7703, 0.0178]]]])
t.shape: torch.Size([3, 4, 5])
ts.shape: torch.Size([1, 3, 4, 5])


tensor([[[[[0.7497, 0.6047, 0.1100, 0.2121, 0.9704],
           [0.8369, 0.2820, 0.3742, 0.0237, 0.4910],
           [0.1235, 0.1143, 0.4725, 0.5751, 0.2952],
           [0.7967, 0.1957, 0.9537, 0.8426, 0.0784]],

          [[0.3756, 0.5226, 0.5730, 0.6186, 0.6962],
           [0.5300, 0.2560, 0.7366

In [16]:
# Reshape tensor
 
print(t.reshape((12,5)))
print(t.reshape(12,-1)) # Can use -1 to specify one of the dimensions which is automatically inferred based on the elements in other dimensions
print(t.reshape(5,4,3))
print(t.reshape(-1))
# print(t.reshape(12,6)) This command won't work as the number of elements need to be consistent with the source tensor

# View
# View works exactly like reshape but may not work in all cases. Please refer to the link below to see how view and reshape are different.
# View vs Reshape
# https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch

tensor([[0.7497, 0.6047, 0.1100, 0.2121, 0.9704],
        [0.8369, 0.2820, 0.3742, 0.0237, 0.4910],
        [0.1235, 0.1143, 0.4725, 0.5751, 0.2952],
        [0.7967, 0.1957, 0.9537, 0.8426, 0.0784],
        [0.3756, 0.5226, 0.5730, 0.6186, 0.6962],
        [0.5300, 0.2560, 0.7366, 0.0204, 0.2036],
        [0.3748, 0.2564, 0.3251, 0.0902, 0.3936],
        [0.6069, 0.1743, 0.4743, 0.8579, 0.4486],
        [0.5139, 0.4569, 0.6012, 0.8179, 0.9736],
        [0.8175, 0.9747, 0.4638, 0.0508, 0.2630],
        [0.8405, 0.4968, 0.2515, 0.1168, 0.0321],
        [0.0780, 0.3986, 0.7742, 0.7703, 0.0178]])
tensor([[0.7497, 0.6047, 0.1100, 0.2121, 0.9704],
        [0.8369, 0.2820, 0.3742, 0.0237, 0.4910],
        [0.1235, 0.1143, 0.4725, 0.5751, 0.2952],
        [0.7967, 0.1957, 0.9537, 0.8426, 0.0784],
        [0.3756, 0.5226, 0.5730, 0.6186, 0.6962],
        [0.5300, 0.2560, 0.7366, 0.0204, 0.2036],
        [0.3748, 0.2564, 0.3251, 0.0902, 0.3936],
        [0.6069, 0.1743, 0.4743, 0.8579, 0.4486],

In [ ]:
# Transpose Tensor
# This operation is primarily a generalization of the regular matrix transpose

t = torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[-1,-2,-3,-4],[-5,-6,-7,-8],[-9,-10,-11,-12]]])

print(t.shape)
print(t)
print('\n')

print(t.transpose(0,1).shape)
print(t.transpose(0,1))
print('\n')

print(t.transpose(0,2).shape)
print(t.transpose(0,2))
print('\n')

torch.Size([2, 3, 4])
tensor([[[  1,   2,   3,   4],
         [  5,   6,   7,   8],
         [  9,  10,  11,  12]],

        [[ -1,  -2,  -3,  -4],
         [ -5,  -6,  -7,  -8],
         [ -9, -10, -11, -12]]])


torch.Size([3, 2, 4])
tensor([[[  1,   2,   3,   4],
         [ -1,  -2,  -3,  -4]],

        [[  5,   6,   7,   8],
         [ -5,  -6,  -7,  -8]],

        [[  9,  10,  11,  12],
         [ -9, -10, -11, -12]]])


torch.Size([4, 3, 2])
tensor([[[  1,  -1],
         [  5,  -5],
         [  9,  -9]],

        [[  2,  -2],
         [  6,  -6],
         [ 10, -10]],

        [[  3,  -3],
         [  7,  -7],
         [ 11, -11]],

        [[  4,  -4],
         [  8,  -8],
         [ 12, -12]]])




`torch.view` has existed for a long time. It will return a tensor with the new shape. The returned tensor will share the underling data with the original tensor. See the documentation here.
On the other hand, it seems that `torch.reshape` has been introduced recently in version 0.4. According to the document, this method will - 

   Returns a tensor with the same data and number of elements as input, but with the specified shape. When possible, the returned tensor will be a view of input. Otherwise, it will be a copy. Contiguous inputs and inputs with compatible strides can be reshaped without copying, but you should not depend on the copying vs. viewing behavior. It means that `torch.reshape` may return a copy or a view of the original tensor. You can not count on that to return a view or a copy. 
    
According to the developer:
if you need a copy use `clone()` if you need the same storage use `view()`. The semantics of `reshape()` are that it may or may not share the storage and you don't know beforehand.
Another difference is that `reshape()` can operate on both contiguous and non-contiguous tensor while `view()` can only operate on contiguous tensor. Also see here about the meaning of contiguous.

In [17]:
# Permute Tensor
# This operation allows the user to simultaneously reorder multiple dimensions unlike transpose which interchanges two dimensions only

t = torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[-1,-2,-3,-4],[-5,-6,-7,-8],[-9,-10,-11,-12]]])

print(t.shape)
print(t)
print('\n')

print(t.permute(1,0,2).shape)
print(t.permute(1,0,2))
print('\n')

print(t.permute(1,2,0).shape)
print(t.permute(1,2,0))
print('\n')

torch.Size([2, 3, 4])
tensor([[[  1,   2,   3,   4],
         [  5,   6,   7,   8],
         [  9,  10,  11,  12]],

        [[ -1,  -2,  -3,  -4],
         [ -5,  -6,  -7,  -8],
         [ -9, -10, -11, -12]]])


torch.Size([3, 2, 4])
tensor([[[  1,   2,   3,   4],
         [ -1,  -2,  -3,  -4]],

        [[  5,   6,   7,   8],
         [ -5,  -6,  -7,  -8]],

        [[  9,  10,  11,  12],
         [ -9, -10, -11, -12]]])


torch.Size([3, 4, 2])
tensor([[[  1,  -1],
         [  2,  -2],
         [  3,  -3],
         [  4,  -4]],

        [[  5,  -5],
         [  6,  -6],
         [  7,  -7],
         [  8,  -8]],

        [[  9,  -9],
         [ 10, -10],
         [ 11, -11],
         [ 12, -12]]])




## Tensor Stack and Repeat
1. Cat
2. Stack
3. Repeat
4. Repeat Interleave
5. Padding

In [ ]:
# Tensor Cat

t1 = torch.rand(size=(2,3,4))
t2 = torch.rand(size=(2,3,4))
t3 = torch.rand(size=(1,3,4))
t4 = torch.rand(size=(2,3,1))

print(t1)
print(t2)
print(t3)
print(t4)

print('Concatenating tensors\n')

print(torch.cat([t1,t2],dim=1))
print(torch.cat([t1,t2,t3],dim=0))
print(torch.cat([t1,t2,t4],dim=2))

tensor([[[0.6965, 0.9143, 0.9351, 0.9412],
         [0.5995, 0.0652, 0.5460, 0.1872],
         [0.0340, 0.9442, 0.8802, 0.0012]],

        [[0.5936, 0.4158, 0.4177, 0.2711],
         [0.6923, 0.2038, 0.6833, 0.7529],
         [0.8579, 0.6870, 0.0051, 0.1757]]])
tensor([[[0.7497, 0.6047, 0.1100, 0.2121],
         [0.9704, 0.8369, 0.2820, 0.3742],
         [0.0237, 0.4910, 0.1235, 0.1143]],

        [[0.4725, 0.5751, 0.2952, 0.7967],
         [0.1957, 0.9537, 0.8426, 0.0784],
         [0.3756, 0.5226, 0.5730, 0.6186]]])
tensor([[[0.6962, 0.5300, 0.2560, 0.7366],
         [0.0204, 0.2036, 0.3748, 0.2564],
         [0.3251, 0.0902, 0.3936, 0.6069]]])
tensor([[[0.1743],
         [0.4743],
         [0.8579]],

        [[0.4486],
         [0.5139],
         [0.4569]]])
Concatenating tensors

tensor([[[0.6965, 0.9143, 0.9351, 0.9412],
         [0.5995, 0.0652, 0.5460, 0.1872],
         [0.0340, 0.9442, 0.8802, 0.0012],
         [0.7497, 0.6047, 0.1100, 0.2121],
         [0.9704, 0.8369, 0.2820

In [ ]:
# Tensor Stack
# This operation can be imagined as a combination of unsqueeze and cat.

t1 = torch.rand(size=(3,4))
t2 = torch.rand(size=(3,4))

print(t1.shape)
print(t1)
print('\n')

print(t2.shape)
print(t2)
print('\n')

print(torch.stack([t1,t2],dim=0).shape)
print(torch.stack([t1,t2],dim=0))

print(torch.stack([t1,t2],dim=1).shape)
print(torch.stack([t1,t2],dim=1))

print(torch.stack([t1,t2],dim=2).shape)
print(torch.stack([t1,t2],dim=2))

torch.Size([3, 4])
tensor([[0.6012, 0.8179, 0.9736, 0.8175],
        [0.9747, 0.4638, 0.0508, 0.2630],
        [0.8405, 0.4968, 0.2515, 0.1168]])


torch.Size([3, 4])
tensor([[0.0321, 0.0780, 0.3986, 0.7742],
        [0.7703, 0.0178, 0.8119, 0.1087],
        [0.3943, 0.2973, 0.4037, 0.4018]])


torch.Size([2, 3, 4])
tensor([[[0.6012, 0.8179, 0.9736, 0.8175],
         [0.9747, 0.4638, 0.0508, 0.2630],
         [0.8405, 0.4968, 0.2515, 0.1168]],

        [[0.0321, 0.0780, 0.3986, 0.7742],
         [0.7703, 0.0178, 0.8119, 0.1087],
         [0.3943, 0.2973, 0.4037, 0.4018]]])
torch.Size([3, 2, 4])
tensor([[[0.6012, 0.8179, 0.9736, 0.8175],
         [0.0321, 0.0780, 0.3986, 0.7742]],

        [[0.9747, 0.4638, 0.0508, 0.2630],
         [0.7703, 0.0178, 0.8119, 0.1087]],

        [[0.8405, 0.4968, 0.2515, 0.1168],
         [0.3943, 0.2973, 0.4037, 0.4018]]])
torch.Size([3, 4, 2])
tensor([[[0.6012, 0.0321],
         [0.8179, 0.0780],
         [0.9736, 0.3986],
         [0.8175, 0.7742]],

  

In [ ]:
# Tensor Repeat

t1 = torch.rand(3)

print('Original t1:')
print(t1)

print('t1.repeat(2)')
print(t1.repeat((2)))

print('t1.repeat(4,2)')
print(t1.repeat((4,2)))

print('t1.repeat(4,2,2)')
print(t1.repeat((4,2,2)))

Original t1:
tensor([0.3191, 0.8249, 0.2995])
t1.repeat(2)
tensor([0.3191, 0.8249, 0.2995, 0.3191, 0.8249, 0.2995])
t1.repeat(4,2)
tensor([[0.3191, 0.8249, 0.2995, 0.3191, 0.8249, 0.2995],
        [0.3191, 0.8249, 0.2995, 0.3191, 0.8249, 0.2995],
        [0.3191, 0.8249, 0.2995, 0.3191, 0.8249, 0.2995],
        [0.3191, 0.8249, 0.2995, 0.3191, 0.8249, 0.2995]])
t1.repeat(4,2,2)
tensor([[[0.3191, 0.8249, 0.2995, 0.3191, 0.8249, 0.2995],
         [0.3191, 0.8249, 0.2995, 0.3191, 0.8249, 0.2995]],

        [[0.3191, 0.8249, 0.2995, 0.3191, 0.8249, 0.2995],
         [0.3191, 0.8249, 0.2995, 0.3191, 0.8249, 0.2995]],

        [[0.3191, 0.8249, 0.2995, 0.3191, 0.8249, 0.2995],
         [0.3191, 0.8249, 0.2995, 0.3191, 0.8249, 0.2995]],

        [[0.3191, 0.8249, 0.2995, 0.3191, 0.8249, 0.2995],
         [0.3191, 0.8249, 0.2995, 0.3191, 0.8249, 0.2995]]])


In [ ]:
# Tensor Repeat Interleave
# Homework 4 Part 2 - Beam Search

t1 = torch.rand(3)
t2 = torch.rand(size=(3,2))

print('Original t1:')
print(t1)

print('Original t2:')
print(t2)

print('t1.repeat_interleave(2)')
print(t1.repeat_interleave(2))

# Unless dimension is specified the multi-dimension tensor is flattened and then interleave operation is applied
print('t2.repeat_interleave(2)')
print(t2.repeat_interleave(2))

print('t2.repeat_interleave(2,dim=0)')
print(t2.repeat_interleave(2,dim=0))

print('t2.repeat_interleave(2,dim=1)')
print(t2.repeat_interleave(2,dim=1))

# Repeat interleave applied with differnet repetitions
print('t2.repeat_interleave(torch.tensor([1,2,3]),dim=0)')
print(t2.repeat_interleave(torch.tensor([1,2,3]),dim=0))

Original t1:
tensor([0.5065, 0.2729, 0.6883])
Original t2:
tensor([[0.0500, 0.4663],
        [0.9397, 0.2961],
        [0.9515, 0.6811]])
t1.repeat_interleave(2)
tensor([0.5065, 0.5065, 0.2729, 0.2729, 0.6883, 0.6883])
t2.repeat_interleave(2)
tensor([0.0500, 0.0500, 0.4663, 0.4663, 0.9397, 0.9397, 0.2961, 0.2961, 0.9515,
        0.9515, 0.6811, 0.6811])
t2.repeat_interleave(2,dim=0)
tensor([[0.0500, 0.4663],
        [0.0500, 0.4663],
        [0.9397, 0.2961],
        [0.9397, 0.2961],
        [0.9515, 0.6811],
        [0.9515, 0.6811]])
t2.repeat_interleave(2,dim=1)
tensor([[0.0500, 0.0500, 0.4663, 0.4663],
        [0.9397, 0.9397, 0.2961, 0.2961],
        [0.9515, 0.9515, 0.6811, 0.6811]])
t2.repeat_interleave(torch.tensor([1,2,3]),dim=0)
tensor([[0.0500, 0.4663],
        [0.9397, 0.2961],
        [0.9397, 0.2961],
        [0.9515, 0.6811],
        [0.9515, 0.6811],
        [0.9515, 0.6811]])


In [ ]:
# Tensor Padding
from torch.nn import functional as F

x = torch.tensor([[1,2,3,4],
                 [1,2,3,4],
                 [1,2,3,4],
                 [1,2,3,4]])

pad_left   = 1
pad_right  = 2
pad_top    = 1
pad_bottom = 2

a = F.pad( x, (pad_left,pad_right,pad_top,pad_bottom), mode = 'constant' )

print(a)

tensor([[0, 0, 0, 0, 0, 0, 0],
        [0, 1, 2, 3, 4, 0, 0],
        [0, 1, 2, 3, 4, 0, 0],
        [0, 1, 2, 3, 4, 0, 0],
        [0, 1, 2, 3, 4, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]])


## Mathematical Operations
1. Point-wise/element-wise operations
1. Redution operations
1. Comparison operations
1. Vector/Matrix operations

In [ ]:
# Point-wise/element-wise operations
# Similar to numpy arrays, torch offers all the basic mathematical operations and is extremely convenient
# Below we list some of the most commonly used operations

t1 = torch.rand(3)
t2 = torch.rand(3)
t3 = torch.rand(size=(3,4))
t4 = torch.rand(size=(3,4))
t5 = torch.rand(size=(3,1))

print('original t1:')
print(t1)

print('original t2:')
print(t2)

print('original t3:')
print(t3)

print('original t4:')
print(t4)

print('original t5:')
print(t5)

# Addition with scalar
print('t1+10')
print(t1+10)

# Addition
print('t1+t2')
print(t1+t2)

# Multiplication with scalar
print('t1*-10')
print(t1*-10)

# Elementwise multiplication
print('t1*t2')
print(t1*t2)

# Absolute value
print('abs(-10*t1)')
print(abs(-10*t1))

# Similar operations extend to multi-dimensional tensors
print('t3+t4')
print(t3+t4)

# Broadcasting b/w arrays of different dimensions
# Note; When broadting two multi-dimensional tensors, match their corresponding dimensions beginning from the last dimension.
# All dimensions should either match or one of the tensor should have length 1 in that specific dimension
print(t3+t5)

original t1:
tensor([0.0488, 0.8163, 0.4423])
original t2:
tensor([0.2768, 0.8998, 0.0960])
original t3:
tensor([[0.5537, 0.3953, 0.8571, 0.6396],
        [0.7403, 0.6766, 0.3798, 0.3948],
        [0.0880, 0.7709, 0.8970, 0.8421]])
original t4:
tensor([[0.1473, 0.5223, 0.1475, 0.2248],
        [0.2086, 0.6709, 0.2020, 0.4891],
        [0.5210, 0.8223, 0.1220, 0.1567]])
original t5:
tensor([[0.2097],
        [0.8500],
        [0.3203]])
t1+10
tensor([10.0488, 10.8163, 10.4423])
t1+t2
tensor([0.3256, 1.7162, 0.5383])
t1*-10
tensor([-0.4877, -8.1635, -4.4230])
t1*t2
tensor([0.0135, 0.7346, 0.0424])
abs(-10*t1)
tensor([0.4877, 8.1635, 4.4230])
t3+t4
tensor([[0.7010, 0.9176, 1.0046, 0.8643],
        [0.9489, 1.3475, 0.5818, 0.8839],
        [0.6090, 1.5932, 1.0190, 0.9989]])
tensor([[0.7633, 0.6050, 1.0667, 0.8492],
        [1.5902, 1.5265, 1.2297, 1.2448],
        [0.4082, 1.0912, 1.2173, 1.1624]])


In [ ]:
# Reduction Operations
# Torch supports all commonly used mathematical reduction operations such as sum(), mean(), std(), max(), argmax(), prod(), unique() etc.
# These can either be applied on the entire tensor or along specific dimensions.

t1 = torch.rand(3)
t2 = torch.rand(size=(3,4))

print('original t1:')
print(t1)

print('original t2:')
print(t2)

print('t1.sum()')
print(t1.sum())

print('t2.sum()')
print(t2.sum())

print('t2.sum(axis=0)')
print(t2.sum(axis=0))

print('t2.sum(axis=1)')
print(t2.sum(axis=1))

original t1:
tensor([0.9217, 0.6808, 0.5633])
original t2:
tensor([[0.4963, 0.4012, 0.5627, 0.3858],
        [0.4965, 0.5638, 0.1089, 0.2379],
        [0.9037, 0.0942, 0.4641, 0.9946]])
t1.sum()
tensor(2.1659)
t2.sum()
tensor(5.7098)
t2.sum(axis=0)
tensor([1.8965, 1.0592, 1.1357, 1.6184])
t2.sum(axis=1)
tensor([1.8460, 1.4071, 2.4567])


In [ ]:
# Comparison Operations

t1 = torch.rand(size=(3,4))
t2 = torch.rand(size=(3,4))
t3 = torch.rand(size=(3,4))

print('original t1:')
print(t1)

print('original t2:')
print(t2)

print('original t3:')
print(t3)

# Basic comparison operations
print('t1>t3')
print(t1>t2)

print('t2!=t3')
print(t2!=t3)

# Combining reduction operations with boolean tensors
print((t1>t2).any())
print((t1>t2).all())
print((t1>t2).any(axis=0))
print((t1>t2).any(axis=1))

print((t2!=t3).any())
print((t2!=t3).all())

original t1:
tensor([[0.6806, 0.5142, 0.0667, 0.7477],
        [0.1439, 0.3581, 0.3322, 0.4260],
        [0.5055, 0.9124, 0.5624, 0.9478]])
original t2:
tensor([[0.8059, 0.1839, 0.7243, 0.1466],
        [0.2881, 0.6471, 0.6651, 0.8751],
        [0.3390, 0.5008, 0.7574, 0.0165]])
original t3:
tensor([[0.8615, 0.0865, 0.5069, 0.4150],
        [0.2367, 0.5661, 0.9135, 0.3538],
        [0.2032, 0.3151, 0.0044, 0.7257]])
t1>t3
tensor([[False,  True, False,  True],
        [False, False, False, False],
        [ True,  True, False,  True]])
t2!=t3
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
tensor(True)
tensor(False)
tensor([ True,  True, False,  True])
tensor([ True, False,  True])
tensor(True)
tensor(True)


In [ ]:
# Vector/Matrix operations
# Torch offers all baisc matrix and vector operations. Moreover there are some helpful utilities which are specific to how data in DL is organized.

# vector x vector
tensor1 = torch.randn(3)
tensor2 = torch.randn(3)

print('tensor1')
print(tensor1)
print('tensor2')
print(tensor2)

print('torch.matmul(tensor1, tensor2)')
print(torch.matmul(tensor1, tensor2))
print(torch.matmul(tensor1, tensor2).size())

# matrix x vector
tensor1 = torch.randn(3, 4)
tensor2 = torch.randn(4)

print('tensor1')
print(tensor1)
print('tensor2')
print(tensor2)

print('torch.matmul(tensor1, tensor2)')
print(torch.matmul(tensor1, tensor2))
print(torch.matmul(tensor1, tensor2).size())

# batched matrix x broadcasted vector
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(4)

print('tensor1')
print(tensor1)
print('tensor2')
print(tensor2)

print('torch.matmul(tensor1, tensor2)')
print(torch.matmul(tensor1, tensor2))
print(torch.matmul(tensor1, tensor2).size())

# batched matrix x batched matrix
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(10, 4, 5)

print('tensor1')
print(tensor1)
print('tensor2')
print(tensor2)

print('torch.matmul(tensor1, tensor2)')
print(torch.matmul(tensor1, tensor2))
print(torch.matmul(tensor1, tensor2).size())

# batched matrix x broadcasted matrix
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(4, 5)

print('tensor1')
print(tensor1)
print('tensor2')
print(tensor2)

print('torch.matmul(tensor1, tensor2)')
print(torch.matmul(tensor1, tensor2))
print(torch.matmul(tensor1, tensor2).size())

tensor1
tensor([1.3565, 0.7341, 0.8062])
tensor2
tensor([ 0.7410,  0.6088, -0.5560])
torch.matmul(tensor1, tensor2)
tensor(1.0037)
torch.Size([])
tensor1
tensor([[ 0.5477,  0.4383,  0.0394, -1.1895],
        [-0.5015, -0.1455,  0.1522, -1.4437],
        [-0.2284, -0.3552, -0.7219, -0.3061]])
tensor2
tensor([ 1.3768,  1.0055, -0.2455, -0.2918])
torch.matmul(tensor1, tensor2)
tensor([ 1.5322, -0.4528, -0.4050])
torch.Size([3])
tensor1
tensor([[[ 0.6257, -1.2231, -0.6232, -0.2162],
         [-0.4887,  0.7870,  0.1076, -1.0715],
         [ 0.3976,  0.6435, -1.1980,  0.4784]],

        [[-1.2295, -1.3700,  1.5435, -0.0332],
         [ 0.4264, -1.1361, -0.1292, -0.0546],
         [ 0.4083,  1.1264,  1.9351,  1.0077]],

        [[-1.5072, -0.5087, -1.2426,  1.2846],
         [ 0.2438,  0.5304, -0.0145, -2.2357],
         [ 0.4900,  0.2908,  0.6442,  3.9300]],

        [[-0.1244,  0.2953,  0.3827, -0.5497],
         [-0.3087, -1.5147,  1.9457, -1.2904],
         [-2.3495, -2.0689,  0.9094, -0.