# Fundamentals of NumPy


## Vectors, Tensors and the Index Notation in NumPy

## Table of Contents
1. Setting-up NumPy
2. NumPy Array Initialization
3. Pivoting the arrays (reshaping, stacking and indexing)
4. Mathematical Operations - matrix multiplication of Arrays
5. Padding Arrays

# 1. Setting up NumPy
You can set install NumPy by using the following command


In [1]:
# !pip install numpy
## If you want to check the version of numpy you are using or if you want to conifrm if it is installed in your system, you can use the following command:
!pip show numpy

Name: numpy
Version: 1.19.1
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: /Users/kalpak/anaconda3/lib/python3.7/site-packages
Requires: 
Required-by: torchvision, torch, tables, statsmodels, seaborn, scipy, scikit-learn, PyWavelets, patsy, pandas, numexpr, numba, mkl-random, mkl-fft, matplotlib, imageio, h5py, Bottleneck, bokeh, bkcharts, astropy


In [ ]:
import numpy as np ## Import NumPy library

# NumPy Arrays

An array is a data structure that stores values of same data type. 

In Python, this is the main difference between arrays and lists.

## 2. Initializing Numpy Arrays

In [ ]:
new_array1 = np.zeros((3, 4))
new_array2 = np.ones((3, 4))
new_array3 = np.zeros((3, 4, 5))

print("First array is:\n", new_array1, "\n")
print("Second array is:\n", new_array2, "\n")
print("Third array is:\n", new_array3, "\n")

First array is:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

Second array is:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

Third array is:
 [[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]] 



Initializing NumPy arrays with random uniform distribution and integers

In [ ]:
new_array1 = np.random.randn(3, 4) #random NumPy array with uniformly distributed numbers
new_array2 = np.random.randint(3, size = (4, 5)) #random NumPy array with randomly distributed integers in the range [0, 3)


print("First array is:\n", new_array1, "\n")
print("Second array is:\n", new_array2, "\n")

First array is:
 [[ 0.54836006 -1.09790719  0.68499552  0.24352909]
 [-0.75137635  0.50689124  1.80352967 -0.2791944 ]
 [ 0.54733619 -0.90171761  1.39432855  0.82409763]] 

Second array is:
 [[2 0 0 1 1]
 [1 2 0 0 2]
 [2 2 0 0 0]
 [1 0 0 2 1]] 



Converting existing data structures to a NumPy array

In [ ]:
#Converting a list to numpy array

list1 = [1, 2, 3, 4, 5]
list_toarray = np.array(list1)

print(list1, type(list1), "\n")
print(list_toarray, type(list_toarray))

[1, 2, 3, 4, 5] <class 'list'> 

[1 2 3 4 5] <class 'numpy.ndarray'>


#3. Pivoting Arrays

Changing dimensions of a NumPy array:
1. Transpose
2. Reshape
3. Flattem
4. Squeeze

In [ ]:
array = np.random.randint(5, size = (3, 4, 5))
print(array, "\n")

## Transpose the array

"""
Transpose is used to reverse or permute the axes of the array. You can specify which axes you want to use for your transpose operation using the "axes"
parameter in np.tranpose.
"""

transposed_array = np.transpose(array)

print("The transposed array looks like: \n", transposed_array)
print(transposed_array.shape, "\n")

## Reshaping the array

"""
Using reshape we can specify the desired shape of the array that we want to end up with. Here we go from rank 3 to rank 2.
"""

reshaped_array = np.reshape(array, (12, 5)) ## Here 'F' stands for Fotran style, there are many other ways of reshaping, please check numpy official documentation
print("The reshaped array looks like \n", reshaped_array, "\n", reshaped_array.shape)

[[[4 1 1 1 2]
  [1 0 3 4 3]
  [4 4 1 1 2]
  [1 2 3 0 4]]

 [[1 1 0 2 1]
  [1 0 2 3 1]
  [0 4 1 2 4]
  [2 0 1 3 1]]

 [[4 1 3 3 4]
  [1 2 2 1 0]
  [2 3 2 0 2]
  [4 4 2 1 1]]] 

The transposed array looks like: 
 [[[4 1 4]
  [1 1 1]
  [4 0 2]
  [1 2 4]]

 [[1 1 1]
  [0 0 2]
  [4 4 3]
  [2 0 4]]

 [[1 0 3]
  [3 2 2]
  [1 1 2]
  [3 1 2]]

 [[1 2 3]
  [4 3 1]
  [1 2 0]
  [0 3 1]]

 [[2 1 4]
  [3 1 0]
  [2 4 2]
  [4 1 1]]]
(5, 4, 3) 

The reshaped array looks like 
 [[4 1 1 1 2]
 [1 0 3 4 3]
 [4 4 1 1 2]
 [1 2 3 0 4]
 [1 1 0 2 1]
 [1 0 2 3 1]
 [0 4 1 2 4]
 [2 0 1 3 1]
 [4 1 3 3 4]
 [1 2 2 1 0]
 [2 3 2 0 2]
 [4 4 2 1 1]] 
 (12, 5)


In [ ]:
## Flattening the numpy array

"""
The flatten operation changes the shape of the array to a 1-D format, and will contain all the elements which existed in the original array.
"""

flattened_array = array.flatten()
print(flattened_array, "\n", "The dimension of the flattened array is:", flattened_array.shape, "\n")


## Squeezing a NumPy array

"""
The squeeze function helps in removing the single dimension entries from the size of your array. If a shape entry of greater than one is selected you 
will receive an error. 
"""

new_array = np.random.randint(3, size = (6, 1, 3))
print("Example of array with single dimension in one of the axis \n", new_array)


squeezed_array = np.squeeze(new_array, axis = 1)

print("The squeezed array is \n",  squeezed_array, "\n and the dimension is", squeezed_array.shape)

[4 1 1 1 2 1 0 3 4 3 4 4 1 1 2 1 2 3 0 4 1 1 0 2 1 1 0 2 3 1 0 4 1 2 4 2 0
 1 3 1 4 1 3 3 4 1 2 2 1 0 2 3 2 0 2 4 4 2 1 1] 
 The dimension of the flattened array is: (60,) 

Example of array with single dimension in one of the axis 
 [[[2 0 1]]

 [[0 0 2]]

 [[1 1 1]]

 [[1 1 1]]

 [[0 1 1]]

 [[1 0 1]]]
The squeezed array is 
 [[2 0 1]
 [0 0 2]
 [1 1 1]
 [1 1 1]
 [0 1 1]
 [1 0 1]] 
 and the dimension is (6, 3)


###Stacking (Combining Tensors)
####Concating and stacking NumPy arrays

Stacking and cocatenating the arrays will come very handy for the assignment part two, especially where will you be required to join arrays to reduce the computational complexity.

In [ ]:
"""Three main types of stacking operations exists in NumPy: hstack vstack and concatenate. 
Here we show you the example of np.concatenate. 
To learn more about hstack and vstack, please see: https://scipython.com/book/chapter-6-numpy/examples/vstack-and-hstack/
"""
array1 = np.random.randint(3, size = (3, 4, 5))
array2 = np.random.randint(4, size = (3, 4, 5))

concatenated_array = np.concatenate((array1, array2), axis = 0) 

"""
Make sure you understand the problem well enough to determine which axis should be used to join the arrays, here we use the first axis.
The resultant array after the concatenation operation depends on the shape of the original arrays used as arguments to pass into the concatenation function.
"""
print("Array 1 is \n", array1, "\n\n")
print("Array 2 is \n", array2, "\n\n")
print("Concatenated array is \n", concatenated_array, "\n\n", "and the dimensions of the concatenated array are: \n", concatenated_array.shape)

Array 1 is 
 [[[2 0 0 2 0]
  [2 2 1 2 2]
  [2 0 1 2 0]
  [2 1 1 1 1]]

 [[1 1 2 2 0]
  [1 1 2 2 1]
  [1 1 2 1 1]
  [2 2 1 1 2]]

 [[0 1 1 2 1]
  [0 2 2 1 1]
  [2 0 1 1 2]
  [1 2 1 2 1]]] 


Array 2 is 
 [[[1 0 3 1 0]
  [2 1 1 1 3]
  [1 0 1 2 1]
  [2 0 2 3 2]]

 [[3 0 0 0 1]
  [2 1 0 3 0]
  [2 1 3 0 1]
  [0 3 1 0 1]]

 [[3 1 3 1 2]
  [3 3 2 2 0]
  [1 1 3 2 1]
  [1 1 3 3 3]]] 


Concatenated array is 
 [[[2 0 0 2 0]
  [2 2 1 2 2]
  [2 0 1 2 0]
  [2 1 1 1 1]]

 [[1 1 2 2 0]
  [1 1 2 2 1]
  [1 1 2 1 1]
  [2 2 1 1 2]]

 [[0 1 1 2 1]
  [0 2 2 1 1]
  [2 0 1 1 2]
  [1 2 1 2 1]]

 [[1 0 3 1 0]
  [2 1 1 1 3]
  [1 0 1 2 1]
  [2 0 2 3 2]]

 [[3 0 0 0 1]
  [2 1 0 3 0]
  [2 1 3 0 1]
  [0 3 1 0 1]]

 [[3 1 3 1 2]
  [3 3 2 2 0]
  [1 1 3 2 1]
  [1 1 3 3 3]]] 

 and the dimensions of the concatenated array are: 
 (6, 4, 5)


###Indexing Arrays

In [ ]:
"""
Indexing is nothing but using the location of an element in an array to extract it.
"""

array = np.random.randint(7, size=(3,4,5))

print('Original array:\n', array, '\n')

# Indexing to access  individual elements in an Array
print('array[0][0][0]\n', array[0][0][0], '\n\n')
print('array[1,2,3]\n', array[1,2,3]), '\n\n'
print('array[-1,-1][-1]\n', array[-1,-1][-1], '\n\n')

# Array Slicing

"""
Array slicing is used to obtain/extract a subset of elements in an array.
"""
print("Indexing the array")
print('array[0]\n', array[0], '\n\n') #extracting all elements from first axis at zeroth location
print('array[:1]\n', array[:1], '\n\n') #
print('array[:,1]\n', array[:,1], '\n\n')
print('array[:,:,3]\n', array[:,:,3], '\n\n')
print('array[:,:,-2:]\n', array[:,:,-2:], '\n\n')

Original array:
 [[[5 3 3 1 6]
  [6 2 6 3 5]
  [6 0 1 0 5]
  [2 2 5 5 6]]

 [[2 6 2 2 1]
  [1 4 3 1 4]
  [6 5 3 1 6]
  [5 5 3 1 1]]

 [[4 6 2 6 0]
  [4 2 0 1 2]
  [0 0 2 0 5]
  [6 0 5 5 6]]] 

array[0][0][0]
 5 


array[1,2,3]
 1
array[-1,-1][-1]
 6 


Indexing the array
array[0]
 [[5 3 3 1 6]
 [6 2 6 3 5]
 [6 0 1 0 5]
 [2 2 5 5 6]] 


array[:1]
 [[[5 3 3 1 6]
  [6 2 6 3 5]
  [6 0 1 0 5]
  [2 2 5 5 6]]] 


array[:,1]
 [[6 2 6 3 5]
 [1 4 3 1 4]
 [4 2 0 1 2]] 


array[:,:,3]
 [[1 3 0 5]
 [2 1 1 1]
 [6 1 0 5]] 


array[:,:,-2:]
 [[[1 6]
  [3 5]
  [0 5]
  [5 6]]

 [[2 1]
  [1 4]
  [1 6]
  [1 1]]

 [[6 0]
  [1 2]
  [0 5]
  [5 6]]] 




#4. Mathematical Operations - Matrix Multiplcation of Arrays

###Element-wise multiplication

In [ ]:
""" This is also known as hadmarad product.
Two arrays (array1 and array2) of the same dimension are multiplied to get a resultant array of the same dimension. Each element (i, j) of the array1 
is multiplied with (i, j) of array2 to get the resultant array.
"""


array1 = np.random.randint(5, size = (2, 4, 5))
array2 = np.random.randint(6, size = (2, 4, 5))

Hadmarad_product = np.multiply(array1, array2) #Which is also equivalent to array1*array2
print("First array, array1 is \n:", array1, "\n")
print("Second array, array2 is \n:", array2, "\n")
print("The element wise product is \n", Hadmarad_product, "\n and the dimension of the resulting product is",  "\n\n",  Hadmarad_product.shape, "\n")



First array, array1 is 
: [[[4 2 0 4 0]
  [3 4 2 4 3]
  [3 0 0 4 4]
  [2 2 3 0 3]]

 [[3 2 1 1 3]
  [1 3 4 4 1]
  [0 0 1 2 3]
  [2 4 1 1 1]]] 

Second array, array2 is 
: [[[4 5 2 3 1]
  [4 0 0 3 3]
  [4 0 0 0 1]
  [3 0 5 3 2]]

 [[1 0 5 3 2]
  [2 3 0 5 4]
  [5 3 5 3 3]
  [3 3 3 1 1]]] 

The element wise product is 
 [[[16 10  0 12  0]
  [12  0  0 12  9]
  [12  0  0  0  4]
  [ 6  0 15  0  6]]

 [[ 3  0  5  3  6]
  [ 2  9  0 20  4]
  [ 0  0  5  6  9]
  [ 6 12  3  1  1]]] 
 and the dimension of the resulting product is 

 (2, 4, 5) 



###Other Multiplications

You are expected to familiarize yourself with Dot Product and TensorDot along with Elementwise multiplication. While going through PyTorch recitation, make sure to review batch-matrix multiplication examples thoroughly as they will be very helpful in the Natural Language Processing assignments.


Here is an example of matrix array multiplication between a $3 \times 1$ matrix array and a $1 \times 3$ matrix array:
$$
\boldsymbol{u} \boldsymbol{v}^T=
\left(\begin{array}{cc} 
u_1 \\
u_2 \\
u_3
\end{array}\right)
\left(\begin{array}{cc} 
v_1 & v_2 & v_3
\end{array}\right)
=
\left(\begin{array}{cc} 
u_1v_1 & u_1v_2 & u_1v_3\\
u_2v_1 & u_2v_2 & u_2v_3\\
u_3v_1 & u_3v_2 & u_3v_3
\end{array}\right)
$$ 

In [ ]:
# Vector/Matrix operations
# Basic matrix and vector operations which will be useful for assignments

# vector x vector
array1 = np.random.randn(3)
array2 = np.random.randn(3)

print('Array1 \n', array1)
print('Array2 \n', array2)

print('Matmul of the two arrays can be derived by using np.matmul(array1, array2) \n', np.matmul(array1, array2))
print("Matmul of the two arrays can also be derived by using array1@array2 \n", array1@array2)
print('Dimensions of resulting product: \n', np.matmul(array1, array2).shape)

# Matrix x Vector
array3 = np.random.randn(3, 4)
array4 = np.random.randn(4)

print('Array3 \n', array3, "\n")
print('Array4 \n', array4, "\n")


print('Matmul of the a vector and a matrix can be derived by using np.matmul(array3, array4) \n', np.matmul(array3, array4))
print('Matmul of the a vector and a matrix can also be derived by using array3@array4 \n', array3@array4)
print('Dimensions of resulting product: \n', np.matmul(array3, array4).shape)

## Matrix x Matrix 

matrix1 = np.random.randint(4, size = (2, 3))
matrix2 = np.random.randint(4, size = (3, 2))

product = matrix1.dot(matrix2)

print('Using DOT: product= \n\n', product, '\n\nproduct.shape =', product.shape)
print("array3@array4 is an equivalent way of dot product \n", matrix1@matrix2, '\n\nproduct.shape =', (matrix1@matrix2).shape)

# Using einsum
product = np.einsum('ik, kj', matrix1, matrix2)
print('\n\nUsing einsum: product= \n\n', product, '\n\nproduct.shape =', product.shape)

# Note, the above einsum notation is equivalent to the following
product = np.einsum('ik, kj -> ij', matrix1, matrix2)


Array1 
 [-0.05789139  0.439855    0.92258965]
Array2 
 [ 1.25150108 -1.92303833  0.01576201]
Matmul of the two arrays can be derived by using np.matmul(array1, array2) 
 -0.9037672967633497
Matmul of the two arrays can also be derived by using array1@array2 
 -0.9037672967633497
Dimensions of resulting product: 
 ()
Array3 
 [[-1.03331536  0.38760718 -0.16636541  0.20838419]
 [ 2.50668619  0.06242275  0.74537117 -1.40103928]
 [-0.05739369 -1.74074739 -1.37376479  0.57244201]] 

Array4 
 [-1.03176142 -0.05445851  1.08532057 -1.19150946] 

Matmul of the a vector and a matrix can be derived by using np.matmul(array3, array4) 
 [ 0.61617488 -0.11138332 -2.01903015]
Matmul of the a vector and a matrix can also be derived by using array3@array4 
 [ 0.61617488 -0.11138332 -2.01903015]
Dimensions of resulting product: 
 (3,)
Using DOT: product= 

 [[16  7]
 [ 8  4]] 

product.shape = (2, 2)


Using einsum: product= 

 [[16  7]
 [ 8  4]] 

product.shape = (2, 2)




###Tensordot

Understanding tensordot function will help you in writing succint code for your homeworks especially in Convolutional Neural Net assignment.

To give a brief overview: 
We input the arrays and the respective axes along which the sum-reductions are intended. The axes that take part in sum-reduction are removed in the output and all of the remaining axes from the input arrays are spread-out as different axes in the output keeping the order in which the input arrays are fed.

To understand in depth please checkout: https://stackoverflow.com/questions/41870228/understanding-tensordot

In [ ]:
A = np.random.randint(9, size=(3))
B = np.random.randint(9, size=(4,4))

print("A = \n", A)

print("B = \n", B)

print("A⨂B =\n", np.tensordot(A, B, axes=0))

A = 
 [7 1 1]
B = 
 [[2 2 3 2]
 [3 5 4 2]
 [6 0 1 8]
 [2 7 1 0]]
A⨂B =
 [[[14 14 21 14]
  [21 35 28 14]
  [42  0  7 56]
  [14 49  7  0]]

 [[ 2  2  3  2]
  [ 3  5  4  2]
  [ 6  0  1  8]
  [ 2  7  1  0]]

 [[ 2  2  3  2]
  [ 3  5  4  2]
  [ 6  0  1  8]
  [ 2  7  1  0]]]


###Sum

These can also be considered as reduction operations. NumPy supports all commonly used mathematical reduction operations such as sum(), mean(), std(), max(), argmax(), unique() etc. These can either be applied on the entire tensor or along specific dimensions.

Please refer to additional NumPy documnetation to familiarize yourself with all operations. The examples below are merely indicative of one reference function.
Link: https://numpy.org/doc/stable/reference/

In [ ]:


array1 = np.random.randint(3, size = (3))
array2 = np.random.randint(3, size=(3,4))

print('Original array1: \n', array1)

print('Original array2: \n', array2)

print('Sum of array1 \n', array1.sum(), "\n\n")
print('Sum of array2 \n', array2.sum(), "\n\n")

print('Sum of array2 elements along axis 0 \n', array2.sum(axis=0), "\n\n")

print('Sum of array2 elements along axis 1 \n', array2.sum(axis=1), "\n\n")

Original array1: 
 [2 2 1]
Original array2: 
 [[2 1 2 1]
 [1 1 0 1]
 [0 2 1 2]]
Sum of array1 
 5 


Sum of array2 
 14 


Sum of array2 elements along axis 0 
 [3 4 3 4] 


Sum of array2 elements along axis 1 
 [6 3 5] 




#5. Padding Arrays

Arrays need to be padded to ensure that computations can be optimized by transfroming the underlying data to become of the same size.

In [ ]:
##Padding arrays at the bottom
a1 = np.array([np.array([3, 1, 4, 1]), 
               np.array([5, 9, 2, 6]), 
               np.array([5, 3, 5, 8])])

"""
Shape 3x4
"""

a2 = np.array([np.array([9, 7, 9, 3]),
               np.array([2, 3, 8, 4])])

"""
Shape 2x4
"""

a3 = np.array([np.array([3, 3, 8, 3]), 
               np.array([2, 7, 9, 5]),
               np.array([0, 2, 8, 8]), 
               np.array([6, 2, 6, 4])])

"""
Shape 4x4
"""

A = np.array([a1, a2, a3])

print("A =\n", A.T)
pad_below1 = 4 - len(a1)
pad_below2 = 4 - len(a2)
pad_below3 = 4 - len(a3)

pad_above = 0
pad_left = 0
par_right = 0

n_add = [((pad_above, pad_below1), (pad_left, par_right)), 
         ((pad_above, pad_below2), (pad_left, par_right)), 
         ((pad_above, pad_below3), (pad_left, par_right)) ]

A3 = [np.pad(A[i], pad_width = n_add[i], mode = 'constant', constant_values = 0) for i in range(3)]
A3 = np.array(A3)

print("A =\n", A)


print("A3 =\n", A3)

A =
 [array([[3, 1, 4, 1],
       [5, 9, 2, 6],
       [5, 3, 5, 8]])
 array([[9, 7, 9, 3],
       [2, 3, 8, 4]])
 array([[3, 3, 8, 3],
       [2, 7, 9, 5],
       [0, 2, 8, 8],
       [6, 2, 6, 4]])]
A =
 [array([[3, 1, 4, 1],
       [5, 9, 2, 6],
       [5, 3, 5, 8]])
 array([[9, 7, 9, 3],
       [2, 3, 8, 4]])
 array([[3, 3, 8, 3],
       [2, 7, 9, 5],
       [0, 2, 8, 8],
       [6, 2, 6, 4]])]
A3 =
 [[[3 1 4 1]
  [5 9 2 6]
  [5 3 5 8]
  [0 0 0 0]]

 [[9 7 9 3]
  [2 3 8 4]
  [0 0 0 0]
  [0 0 0 0]]

 [[3 3 8 3]
  [2 7 9 5]
  [0 2 8 8]
  [6 2 6 4]]]


In [ ]:
##Padding arrays at the top
pad_above1 = 4 - len(a1)
pad_above2 = 4 - len(a2)
pad_above3 = 4 - len(a3)

pad_below = 0
pad_left = 0
par_right = 0

n_add = [((pad_above1, pad_below), (pad_left, par_right)), 
         ((pad_above2, pad_below), (pad_left, par_right)), 
         ((pad_above3, pad_below), (pad_left, par_right))]

A4 = [np.pad(A[i], pad_width = n_add[i], mode = 'constant', constant_values = 0) for i in range(3)]
A4 = np.array(A4)

print("A =\n", A)

print("A4 =\n", A4)

A =
 [array([[3, 1, 4, 1],
       [5, 9, 2, 6],
       [5, 3, 5, 8]])
 array([[9, 7, 9, 3],
       [2, 3, 8, 4]])
 array([[3, 3, 8, 3],
       [2, 7, 9, 5],
       [0, 2, 8, 8],
       [6, 2, 6, 4]])]
A4 =
 [[[0 0 0 0]
  [3 1 4 1]
  [5 9 2 6]
  [5 3 5 8]]

 [[0 0 0 0]
  [0 0 0 0]
  [9 7 9 3]
  [2 3 8 4]]

 [[3 3 8 3]
  [2 7 9 5]
  [0 2 8 8]
  [6 2 6 4]]]
